In [1]:
import numpy as np

In [2]:
#Generating random numbers
randNumbers = np.random.randint(1,150,500)

In [3]:
randNumbers

array([ 22,  93, 120,   5, 132,  56, 107,  93, 132,  43,  71,  43,  88,
        94, 145,  37,  16, 109, 147, 132,  38,  49,   1, 148,  49,  35,
        28,   2,  80, 133, 118,   1, 139,  29,  46, 149, 117,  86,  78,
       107,  25, 120, 133,   7,  75,  25,  83, 141,  62, 117,  68,  22,
        71, 129,  38,  87, 125,  30, 111,   8, 146, 144,   1, 143,  89,
         1,  48, 145,  66,  29,  35, 110,  89, 136,   1,  40,  63, 135,
        68,  39,  79,  15,  38,  33,  46, 146, 113,  71,  29,  17,  37,
       143,  35,  97,  93, 115, 144,  91,  69,  12,   7, 113, 149,  16,
         7, 148,  93, 109, 114,  14,  98,   3, 133,  12, 121,  72, 134,
        98, 143, 142,  20, 136,  13,  64, 100,  17, 103,  33, 131,  27,
        52, 142,  69, 149,  14,  64,  74,  65, 108,  32,  41,  32,  36,
        57,  18, 133, 147,  20, 142,  66,  51, 128, 141, 117,  43,  45,
       132,  84,  97,  66,   6,  74,  23, 121,  61,   3, 100,  97,  75,
        80,  90,  88,  20,  84, 127,  51,  81,  19,   1, 119, 11

In [23]:
#Sort the numbers before finding percentile
#percentile should be less than 100% otherwise there is no point in finding them
# formula for percentile = #percentile Needed
#                           ------------------- X (n + 1)
#                                 100

#Percentile Rank of x = #of values below x
#                        ------------------- X 100
#                                n


randNumbers.sort()
print(randNumbers)
for i in range(0,randNumbers.size,10):
    if i < 100:
        p = np.percentile(randNumbers,i)
        print ("The i",i,"th percentile is :",p)


[  1   1   1   1   1   1   1   1   2   2   2   2   3   3   3   4   4   4
   5   5   6   6   7   7   7   7   8   8   8   9   9   9  10  10  10  10
  10  10  10  11  12  12  13  13  13  14  14  14  15  15  15  16  16  16
  16  17  17  17  18  18  19  19  19  19  19  20  20  20  20  20  20  21
  21  21  21  22  22  22  23  23  23  24  24  25  25  26  26  27  27  28
  28  29  29  29  29  29  29  29  29  29  30  30  32  32  32  32  33  33
  33  33  33  33  34  34  34  34  35  35  35  35  35  36  36  36  37  37
  38  38  38  38  38  38  38  39  39  39  40  40  40  41  41  41  41  41
  42  43  43  43  44  44  44  44  44  45  45  46  46  46  46  46  47  47
  47  48  49  49  49  49  50  50  51  51  51  52  52  52  53  53  53  54
  54  54  55  55  55  55  56  56  56  56  56  56  56  56  57  57  57  57
  58  59  59  59  60  61  61  61  62  62  63  63  64  64  64  64  65  65
  66  66  66  67  67  67  67  68  68  68  68  69  69  70  71  71  71  71
  71  72  72  72  72  73  73  74  74  74  74  74  7

In [15]:
#the 50th percentile is Median
median = np.percentile(randNumbers,50)
median

75.5

array([  1,   1,   1,   1,   1,   1,   1,   1,   2,   2,   2,   2,   3,
         3,   3,   4,   4,   4,   5,   5,   6,   6,   7,   7,   7,   7,
         8,   8,   8,   9,   9,   9,  10,  10,  10,  10,  10,  10,  10,
        11,  12,  12,  13,  13,  13,  14,  14,  14,  15,  15,  15,  16,
        16,  16,  16,  17,  17,  17,  18,  18,  19,  19,  19,  19,  19,
        20,  20,  20,  20,  20,  20,  21,  21,  21,  21,  22,  22,  22,
        23,  23,  23,  24,  24,  25,  25,  26,  26,  27,  27,  28,  28,
        29,  29,  29,  29,  29,  29,  29,  29,  29,  30,  30,  32,  32,
        32,  32,  33,  33,  33,  33,  33,  33,  34,  34,  34,  34,  35,
        35,  35,  35,  35,  36,  36,  36,  37,  37,  38,  38,  38,  38,
        38,  38,  38,  39,  39,  39,  40,  40,  40,  41,  41,  41,  41,
        41,  42,  43,  43,  43,  44,  44,  44,  44,  44,  45,  45,  46,
        46,  46,  46,  46,  47,  47,  47,  48,  49,  49,  49,  49,  50,
        50,  51,  51,  51,  52,  52,  52,  53,  53,  53,  54,  5

In [17]:
from scipy import stats

In [18]:
m = stats.mode(randNumbers)
m

ModeResult(mode=array([29]), count=array([9]))

In [19]:
from scipy.stats import itemfreq

In [20]:
itemfreq(randNumbers)

array([[  1,   8],
       [  2,   4],
       [  3,   3],
       [  4,   3],
       [  5,   2],
       [  6,   2],
       [  7,   4],
       [  8,   3],
       [  9,   3],
       [ 10,   7],
       [ 11,   1],
       [ 12,   2],
       [ 13,   3],
       [ 14,   3],
       [ 15,   3],
       [ 16,   4],
       [ 17,   3],
       [ 18,   2],
       [ 19,   5],
       [ 20,   6],
       [ 21,   4],
       [ 22,   3],
       [ 23,   3],
       [ 24,   2],
       [ 25,   2],
       [ 26,   2],
       [ 27,   2],
       [ 28,   2],
       [ 29,   9],
       [ 30,   2],
       [ 32,   4],
       [ 33,   6],
       [ 34,   4],
       [ 35,   5],
       [ 36,   3],
       [ 37,   2],
       [ 38,   7],
       [ 39,   3],
       [ 40,   3],
       [ 41,   5],
       [ 42,   1],
       [ 43,   3],
       [ 44,   5],
       [ 45,   2],
       [ 46,   5],
       [ 47,   3],
       [ 48,   1],
       [ 49,   4],
       [ 50,   2],
       [ 51,   3],
       [ 52,   3],
       [ 53,   3],
       [ 54,

In [22]:
randNumbers.mean()

75.394000000000005